#!/usr/bin/env python3

import time
import colors as c

count_length = 0.38

snake = '''
                 _        
                | |       
 ___ _ __   __ _| | _____ 
/ __| '_ \ / _` | |/ / _ \\
\__ \ | | | (_| |   <  __
|___/_| |_|\__,_|_|\_\___|

'''
while True:
    c.clear_screen()

    for verse in range(5):

        for badger in range(11):
            print(c.yellow + 'badger!' + c.reset)
            time.sleep(count_length)

        if verse < 4:
            for mushroom in range(4):
                print(c.magenta + 'mushroom.' + c.reset)
                time.sleep(count_length * 2)
        else:
            print(snake)
            time.sleep(count_length * 11)

        c.clear_screen()
