#!/usr/bin/env python3

import colors as c
import random

sides = []

sides.append('''
  -------
 |       |
 |   I   | 
 |      1|
  -------
''')

sides.append('''
  ------
 |      |
 |  II  |
 |     2| 
  ------
''')

sides.append('''
  -------
 |       |
 |  III  |
 |      3|
  -------
''')

sides.append('''
  ------
 |      |
 |  IV  |
 |     4|
  ------
''')


sides.append('''
  -------
 |       |
 |   V   |
 |      5|
  -------
''')

sides.append('''
  ------
 |      |
 |  VI  |
 |     6|
  ------
''')

while True:
    side = random.choice(sides)
    print(c.clear + c.random_color() + side + c.reset)
    input()



