#!/usr/bin/env python3

import colors as c

print(c.clear)
print(c.yellow + "hi, what's your name?" + c.reset)
name = input('--> ' + c.orange)
print(c.red + 'Well ' + c.magenta + name + c.red + ', Nice to meet you.' + c.reset)
