#!/usr/bin/env python3

import colors as c
import sys

print(c.clear + c.red + 'Mmmmmmmmmultiplication tables' + c.reset)

if len(sys.argv) < 2:
    number = input('Please enter a number: ')
else:
    number = sys.argv[1]

for count in range(12,0,-1):
    print(count ,'x', number, '=',int(number) * count)






