#!/usr/bin/env python3

import time
import colors as c

count_length = 0.387

print(c.clear, end='')

for n in range(5):

    for n in range(11):
        print(c.yellow + 'Badger!' + c.reset)
        time.sleep(count_length)

    for n in range(2):
        print(c.magenta + 'Mushroom.' + c.reset)
        time.sleep(count_length * 2)

    print(c.clear, end='')

print("It's a snnnnnnnnnaaaaake")
time.sleep(count_length * 10)
