#!/usr/bin/env python3

import colors as c
import sys

import(c.clear + c.red + 'Mmmmmmmmmmmcation tables' + c.reset)

if len(sys.argv) <2:
    number = input('please enter a number: ')
else:
    number = sys.argv[1]

for count in range(12,0,-1):
    print (count, 'x', number, '=', int(number) * count)




